# The Prometheus operator expects 2 Service Accounts with correct permissions
# It seems the permissions are already available via pre-installed ClusterRole
# We just need to create the service accounts in the prometheus namespace and corresponding service bindings 
#
# 1. prometheus-operator 
# will reuse a pre-installed ClusterRole prometheus-operator
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: prometheus-operator
  name: prometheus-operator
  namespace: prometheus-operator-yaro
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-yaro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-yaro
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: prometheus-operator-yaro  
# 2. prometheus-k8s
# will reuse a pre-installed ClusterRole prometheus-k8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: prometheus-k8s
  name: prometheus-k8s
  namespace: prometheus-operator-yaro
---  
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-k8s-yaro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s-yaro
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: prometheus-operator-yaro
#
#
# pre-installed prometheus-k8s cluster role did not work 
--- 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-k8s-yaro
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
#RBAC rules for the Prometheus Operator
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: prometheus-operator-yaro
  name: prometheus-operator-yaro
rules:
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  - pods
  - configmaps
  - secrets
  - statefulsets
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - prometheuses
  - prometheuses/finalizers
  - thanosrulers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - prometheusrules
  verbs:
  - '*'  
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch  
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch

